ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.repeated_sender]
path = "out/RepeatedSenderTrap.sol/RepeatedSenderTrap.json"
trap_contract = "0xA8625B0f1c7A8b42c928308aB7ed78f739b18F06"
response_contract = "0x4FFA9bbaB1F6d4C2999523aC1715185a02606275"
response_function = "respondWithRepeatedSenderAlert(address,uint256)"
cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private_trap = true
whitelist = ["0x43f89ee2ac9f93ed5e8913034bb9275630254d57"]
