ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps.repeated_sender]
path = "out/RepeatedSenderTrap.sol/RepeatedSenderTrap.json"
trap_contract = "0xa3c724233d90dE271b357e6919690f308fFd2Db7"
response_contract = "0xfF38560436f3eB6869d926b942a94773F8f9254a"
response_function = "respondWithRepeatedSenderAlert(address,uint256)"
cooldown_period_blocks = 20
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 1
private_trap = true
whitelist = ["0x43f89ee2ac9f93ed5e8913034bb9275630254d57"]
